### ISSUE TITLE
Cannot log into Bitbucket

### ISSUE THREAD

**Issue by FranklinYu** [johnmichel/Library-Detector-for-Chrome#164]
See https://stackoverflow.com/questions/58057926/unable-to-log-into-bitbucket-on-chrome#59866112.

**Comment by housseindjirdeh** [comment]
Oh wow interesting. Thanks for opening this, I'll take a look soon as I get time!

**Comment by johnmichel** [comment]
This should be resolved now that #172 is merged

**Comment by FranklinYu** [comment]
The reset-password workflow is still broken; I got error when setting new password.

**Comment by johnmichel** [comment]
> The reset-password workflow is still broken; I got error when setting new password.

I've published the changes made as [`v6.0.0`](9b25c32391202854a0a78c6a15f7e60661b86bdf) and submitted it to the Chrome Web Store as an update.  Hopefully it will move through the review process quickly and will resolve the issue.
